# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build test-workspace`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t test-workspace`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system test-workspace && \
          adduser --system -G test-workspace test-workspace

COPY dist/test-workspace test-workspace
RUN chown -R test-workspace:test-workspace .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix test-workspace --omit=dev -f install

CMD [ "node", "test-workspace" ]
